### ISSUE TITLE
Unable to install on MacOS

### ISSUE THREAD

**Issue by s0rthak** [haroldadmin/getignore#7]
Hi, I tried installing the package for macOS and got a `404`. I am currently on Big Sur

```
➜   git:(main) brew install getignore 
==> Installing getignore from haroldadmin/getignore
==> Downloading https://github.com/haroldadmin/homebrew-getignore/releases/download/getignore-0.1.0/getignore-0.2.0.catalina.bottle.tar.gz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "getignore"
Download failed: https://github.com/haroldadmin/homebrew-getignore/releases/download/getignore-0.1.0/getignore-0.2.0.catalina.bottle.tar.gz
```

**Comment by haroldadmin** [comment]
Thanks for reporting the issue, this looks like a major oversight and the result of my lack of familiarity with Homebrew's publishing process.

The problem seems to lie in [Homebrew Formula](https://github.com/haroldadmin/homebrew-getignore/blob/f6b97abb2baa2a9752ea689ad51e874da1841fc7/Formula/getignore.rb#L9) for this package. I'll submit a fix for this ASAP.

As a _temporary_ workaround, you can install the package using any of the following methods:

**Manual**:
- Download the binary for your OS/Arch from [Releases](https://github.com/haroldadmin/getignore/releases/tag/0.2.0)
- Place the binary in directory on your `PATH`, and restart your terminal

**Install using Go**
- Install the [Go](https://go.dev/dl/) programming language
- Run `go install github.com/haroldadmin/getignore`

**Compile from source**
- Install the [Go](https://go.dev/dl/) programming language
- Clone this repository locally
- `cd` to the repository, and run `go install`

**Comment by haroldadmin** [comment]
I have automated Homebrew publishing using the fantastic [`goreleaser`](https://goreleaser.com/) tool. You should now be able to install v0.2.1 without any problems. 

Please try it again and report back when you get a chance!

**Comment by s0rthak** [comment]
Working now. Thanks for the quick help!
